# Site
name: 'News / yEAh Network'
description: 'All news relating to yEAh Games is published directly to this library collection.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'admin@yeahgames.net'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /news/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    tallinn:
      name:           Tallinn
      site:           https://t.unigon.net
      avatar:         //news.yeahgames.net/assets/images/avatar2.jpg
      bio:            "Lead developer, writer and administrator for yEAh Games."
      email:          tallinn@yeahgames.net
      twitter:        https://github.com/nnillat

    yeahgames:
      name:           yEAh Games
      site:           https://www.yeahgames.net
      avatar:         //news.yeahgames.net/assets/images/logo.png/
      bio:            "Official yEAh Games News publications." #yEAH GAMES MUST ALWAYS BE A CREDITED AUTHOR ON ALL POSTS! THE AUTHOR CAN ADD THEIR CREDIT AS WELL IN CERTAIN CASES, BUT YEAHGAMES MUST ALWAYS BE THERE
      email:          admin@yeahgames.net
      twitter:        https://github.com/yeah-games

    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         //news.yeahgames.net/assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         //news.yeahgames.net/assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]