# Site
name: 'News • Library / yEAh Network'
description: 'All news relating to yEAh Games is published directly to this library collection.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'admin@yeahgames.net'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /news/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    yeahgames:
      name:           yEAh Games (@yeahgames)
      site:           https://www.yeahgames.net
      avatar:         //cdn.yeahgames.net/img/members/profile/default/@yeahgames.png
      bio:            "Official yEAh Games News publications." #yEAH GAMES MUST ALWAYS BE A CREDITED AUTHOR ON ALL POSTS! THE AUTHOR CAN ADD THEIR CREDIT AS WELL IN CERTAIN CASES, BUT YEAHGAMES MUST ALWAYS BE THERE
      email:          admin@yeahgames.net
      twitter:        https://github.com/yeah-games

    tallinn:
      name:           Tallinn (@nnillat)
      site:           https://t.unigon.net
      avatar:         //cdn.yeahgames.net/img/members/profile/default/@nnillat.png
      bio:            "Lead developer, writer and administrator for yEAh Games."
      email:          tallinn@yeahgames.net
      twitter:        https://github.com/nnillat      

    aidan:
      name:           Aidan (@undone)
      site:           https://members.yeahgames.net/@undone
      avatar:         //cdn.yeahgames.net/img/members/pfp/default/@undone.png
      bio:            "Secondary developer, writer, administrator for yEAh Games."
      email:          aidan@yeahgames.net
      twitter:        https://github.com/undonesundew   
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]